module.exports = {
	dictionary: function() {
		return {

			// MOVES

			'はたく': 'Pound',
			'からてチョップ': 'Karate Chop',
			'おうふくビンタ': 'Double Slap',
			'れんぞくパンチ': 'Comet Punch',
			'メガトンパンチ': 'Mega Punch',
			'ネコにこばん': 'Pay Day',
			'ほのおのパンチ': 'Fire Punch',
			'れいとうパンチ': 'Ice Punch',
			'かみなりパンチ': 'Thunder Punch',
			'ひっかく': 'Scratch',
			'はさむ': 'Vice Grip',
			'ハサミギロチン': 'Guillotine',
			'かまいたち': 'Razor Wind',
			'つるぎのまい': 'Swords Dance',
			'いあいぎり': 'Cut',
			'かぜおこし': 'Gust',
			'つばさでうつ': 'Wing Attack',
			'ふきとばし': 'Whirlwind',
			'そらをとぶ': 'Fly',
			'しめつける': 'Bind',
			'たたきつける': 'Slam',
			'つるのムチ': 'Vine Whip',
			'ふみつけ': 'Stomp',
			'にどげり': 'Double Kick',
			'メガトンキック': 'Mega Kick',
			'とびげり': 'Jump Kick',
			'まわしげり': 'Rolling Kick',
			'すなかけ': 'Sand Attack',
			'ずつき': 'Headbutt',
			'つのでつく': 'Horn Attack',
			'みだれづき': 'Fury Attack',
			'つのドリル': 'Horn Drill',
			'たいあたり': 'Tackle',
			'のしかかり': 'Body Slam',
			'まきつく': 'Wrap',
			'とっしん': 'Take Down',
			'あばれる': 'Thrash',
			'すてみタックル': 'Double-Edge',
			'しっぽをふる': 'Tail Whip',
			'どくばり': 'Poison Sting',
			'ダブルニードル': 'Twineedle',
			'ミサイルばり': 'Pin Missile',
			'にらみつける': 'Leer',
			'かみつく': 'Bite',
			'なきごえ': 'Growl',
			'ほえる': 'Roar',
			'うたう': 'Sing',
			'ちょうおんぱ': 'Supersonic',
			'ソニックブーム': 'Sonic Boom',
			'かなしばり': 'Disable',
			'ようかいえき': 'Acid',
			'ひのこ': 'Ember',
			'かえんほうしゃ': 'Flamethrower',
			'しろいきり': 'Mist',
			'みずでっぽう': 'Water Gun',
			'ハイドロポンプ': 'Hydro Pump',
			'なみのり': 'Surf',
			'れいとうビーム': 'Ice Beam',
			'サイケこうせん': 'Psybeam',
			'バブルこうせん': 'Bubble Beam',
			'オーロラビーム': 'Aurora Beam',
			'はかいこうせん': 'Hyper Beam',
			'つつく': 'Peck',
			'ドリルくちばし': 'Drill Peck',
			'じごくぐるま': 'Submission',
			'けたぐり': 'Low Kick',
			'カウンター': 'Counter',
			'ちきゅうなげ': 'Seismic Toss',
			'かいりき': 'Strength',
			'すいとる': 'Absorb',
			'メガドレイン': 'Mega Drain',
			'やどりぎのたね': 'Leech Seed',
			'せいちょう': 'Growth',
			'はっぱカッター': 'Razor Leaf',
			'ソーラービーム': 'Solar Beam',
			'どくのこな': 'Poison Powder',
			'しびれごな': 'Stun Spore',
			'ねむりごな': 'Sleep Powder',
			'はなびらのまい': 'Petal Dance',
			'いとをはく': 'String Shot',
			'りゅうのいかり': 'Dragon Rage',
			'ほのおのうず': 'Fire Spin',
			'でんきショック': 'Thunder Shock',
			'10まんボルト': 'Thunderbolt',
			'10万ボルト': 'Thunderbolt',
			'でんじは': 'Thunder Wave',
			'かみなり': 'Thunder',
			'いわおとし': 'Rock Throw',
			'じしん': 'Earthquake',
			'じわれ': 'Fissure',
			'あなをほる': 'Dig',
			'どくどく': 'Toxic',
			'ねんりき': 'Confusion',
			'サイコキネシス': 'Psychic',
			'さいみんじゅつ': 'Hypnosis',
			'ヨガのポーズ': 'Meditate',
			'こうそくいどう': 'Agility',
			'でんこうせっか': 'Quick Attack',
			'テレポート': 'Teleport',
			'ナイトヘッド': 'Night Shade',
			'ものまね': 'Mimic',
			'いやなおと': 'Screech',
			'かげぶんしん': 'Double Team',
			'じこさいせい': 'Recover',
			'かたくなる': 'Harden',
			'ちいさくなる': 'Minimize',
			'えんまく': 'Smokescreen',
			'あやしいひかり': 'Confuse Ray',
			'からにこもる': 'Withdraw',
			'まるくなる': 'Defense Curl',
			'バリアー': 'Barrier',
			'ひかりのかべ': 'Light Screen',
			'くろいきり': 'Haze',
			'リフレクター': 'Reflect',
			'きあいだめ': 'Focus Energy',
			'がまん': 'Bide',
			'ゆびをふる': 'Metronome',
			'オウムがえし': 'Mirror Move',
			'じばく': 'Self-Destruct',
			'タマゴばくだん': 'Egg Bomb',
			'したでなめる': 'Lick',
			'スモッグ': 'Smog',
			'ヘドロこうげき': 'Sludge',
			'ホネこんぼう': 'Bone Club',
			'だいもんじ': 'Fire Blast',
			'たきのぼり': 'Waterfall',
			'からではさむ': 'Clamp',
			'スピードスター': 'Swift',
			'ロケットずつき': 'Skull Bash',
			'とげキャノン': 'Spike Cannon',
			'からみつく': 'Constrict',
			'ドわすれ': 'Amnesia',
			'スプーンまげ': 'Kinesis',
			'タマゴうみ': 'Soft-Boiled',
			'とびひざげり': 'High Jump Kick',
			'へびにらみ': 'Glare',
			'ゆめくい': 'Dream Eater',
			'どくガス': 'Poison Gas',
			'たまなげ': 'Barrage',
			'きゅうけつ': 'Leech Life',
			'あくまのキッス': 'Lovely Kiss',
			'ゴッドバード': 'Sky Attack',
			'へんしん': 'Transform',
			'あわ': 'Bubble',
			'ピヨピヨパンチ': 'Dizzy Punch',
			'キノコのほうし': 'Spore',
			'フラッシュ': 'Flash',
			'サイコウェーブ': 'Psywave',
			'はねる': 'Splash',
			'とける': 'Acid Armor',
			'クラブハンマー': 'Crabhammer',
			'だいばくはつ': 'Explosion',
			'みだれひっかき': 'Fury Swipes',
			'ホネブーメラン': 'Bonemerang',
			'いわなだれ': 'Rock Slide',
			'ひっさつまえば': 'Hyper Fang',
			'かくばる': 'Sharpen',
			'テクスチャー': 'Conversion',
			'トライアタック': 'Tri Attack',
			'いかりのまえば': 'Super Fang',
			'きりさく': 'Slash',
			'みがわり': 'Substitute',
			'わるあがき': 'Struggle',
			'スケッチ': 'Sketch',
			'トリプルキック': 'Triple Kick',
			'どろぼう': 'Thief',
			'クモのす': 'Spider Web',
			'こころのめ': 'Mind Reader',
			'あくむ': 'Nightmare',
			'かえんぐるま': 'Flame Wheel',
			'いびき': 'Snore',
			'のろい': 'Curse',
			'じたばた': 'Flail',
			'テクスチャー２': 'Conversion 2',
			'エアロブラスト': 'Aeroblast',
			'わたほうし': 'Cotton Spore',
			'きしかいせい': 'Reversal',
			'うらみ': 'Spite',
			'こなゆき': 'Powder Snow',
			'まもる': 'Protect',
			'守る': 'Protect',
			'マッハパンチ': 'Mach Punch',
			'こわいかお': 'Scary Face',
			'だましうち': 'Feint Attack',
			'てんしのキッス': 'Sweet Kiss',
			'はらだいこ': 'Belly Drum',
			'ヘドロばくだん': 'Sludge Bomb',
			'どろかけ': 'Mud-Slap',
			'オクタンほう': 'Octazooka',
			'まきびし': 'Spikes',
			'でんじほう': 'Zap Cannon',
			'みやぶる': 'Foresight',
			'みちづれ': 'Destiny Bond',
			'ほろびのうた': 'Perish Song',
			'こごえるかぜ': 'Icy Wind',
			'みきり': 'Detect',
			'ボーンラッシュ': 'Bone Rush',
			'ロックオン': 'Lock-On',
			'げきりん': 'Outrage',
			'すなあらし': 'Sandstorm',
			'ギガドレイン': 'Giga Drain',
			'こらえる': 'Endure',
			'あまえる': 'Charm',
			'ころがる': 'Rollout',
			'みねうち': 'False Swipe',
			'いばる': 'Swagger',
			'ミルクのみ': 'Milk Drink',
			'スパーク': 'Spark',
			'れんぞくぎり': 'Fury Cutter',
			'はがねのつばさ': 'Steel Wing',
			'くろいまなざし': 'Mean Look',
			'メロメロ': 'Attract',
			'ねごと': 'Sleep Talk',
			'いやしのすず': 'Heal Bell',
			'おんがえし': 'Return',
			'プレゼント': 'Present',
			'やつあたり': 'Frustration',
			'しんぴのまもり': 'Safeguard',
			'いたみわけ': 'Pain Split',
			'せいなるほのお': 'Sacred Fire',
			'マグニチュード': 'Magnitude',
			'ばくれつパンチ': 'Dynamic Punch',
			'メガホーン': 'Megahorn',
			'りゅうのいぶき': 'Dragon Breath',
			'バトンタッチ': 'Baton Pass',
			'アンコール': 'Encore',
			'おいうち': 'Pursuit',
			'こうそくスピン': 'Rapid Spin',
			'あまいかおり': 'Sweet Scent',
			'アイアンテール': 'Iron Tail',
			'メタルクロー': 'Metal Claw',
			'あてみなげ': 'Vital Throw',
			'あさのひざし': 'Morning Sun',
			'こうごうせい': 'Synthesis',
			'つきのひかり': 'Moonlight',
			'クロスチョップ': 'Cross Chop',
			'たつまき': 'Twister',
			'あまごい': 'Rain Dance',
			'にほんばれ': 'Sunny Day',
			'かみくだく': 'Crunch',
			'ミラーコート': 'Mirror Coat',
			'じこあんじ': 'Psych Up',
			'しんそく': 'Extreme Speed',
			'げんしのちから': 'Ancient Power',
			'シャドーボール': 'Shadow Ball',
			'みらいよち': 'Future Sight',
			'いわくだき': 'Rock Smash',
			'うずしお': 'Whirlpool',
			'ふくろだたき': 'Beat Up',
			'ねこだまし': 'Fake Out',
			'さわぐ': 'Uproar',
			'たくわえる': 'Stockpile',
			'はきだす': 'Spit Up',
			'のみこむ': 'Swallow',
			'ねっぷう': 'Heat Wave',
			'あられ': 'Hail',
			'いちゃもん': 'Torment',
			'おだてる': 'Flatter',
			'おにび': 'Will-O-Wisp',
			'おきみやげ': 'Memento',
			'からげんき': 'Facade',
			'きあいパンチ': 'Focus Punch',
			'きつけ': 'Smelling Salts',
			'このゆびとまれ': 'Follow Me',
			'しぜんのちから': 'Nature Power',
			'じゅうでん': 'Charge',
			'ちょうはつ': 'Taunt',
			'てだすけ': 'Helping Hand',
			'なりきり': 'Role Play',
			'ねがいごと': 'Wish',
			'ねこのて': 'Assist',
			'ねをはる': 'Ingrain',
			'ばかぢから': 'Superpower',
			'マジックコート': 'Magic Coat',
			'リサイクル': 'Recycle',
			'リベンジ': 'Revenge',
			'かわらわり': 'Brick Break',
			'あくび': 'Yawn',
			'はたきおとす': 'Knock Off',
			'がむしゃら': 'Endeavor',
			'ふんか': 'Eruption',
			'スキルスワップ': 'Skill Swap',
			'ふういん': 'Imprison',
			'リフレッシュ': 'Refresh',
			'おんねん': 'Grudge',
			'よこどり': 'Snatch',
			'ひみつのちから': 'Secret Power',
			'ダイビング': 'Dive',
			'つっぱり': 'Arm Thrust',
			'ほごしょく': 'Camouflage',
			'ほたるび': 'Tail Glow',
			'ラスターパージ': 'Luster Purge',
			'ミストボール': 'Mist Ball',
			'フェザーダンス': 'Feather Dance',
			'フラフラダンス': 'Teeter Dance',
			'ブレイズキック': 'Blaze Kick',
			'どろあそび': 'Mud Sport',
			'アイスボール': 'Ice Ball',
			'ニードルアーム': 'Needle Arm',
			'なまける': 'Slack Off',
			'ハイパーボイス': 'Hyper Voice',
			'どくどくのキバ': 'Poison Fang',
			'ブレイククロー': 'Crush Claw',
			'ブラストバーン': 'Blast Burn',
			'ハイドロカノン': 'Hydro Cannon',
			'コメットパンチ': 'Meteor Mash',
			'おどろかす': 'Astonish',
			'ウェザーボール': 'Weather Ball',
			'アロマセラピー': 'Aromatherapy',
			'うそなき': 'Fake Tears',
			'エアカッター': 'Air Cutter',
			'オーバーヒート': 'Overheat',
			'かぎわける': 'Odor Sleuth',
			'がんせきふうじ': 'Rock Tomb',
			'ぎんいろのかぜ': 'Silver Wind',
			'きんぞくおん': 'Metal Sound',
			'くさぶえ': 'Grass Whistle',
			'くすぐる': 'Tickle',
			'コスモパワー': 'Cosmic Power',
			'しおふき': 'Water Spout',
			'シグナルビーム': 'Signal Beam',
			'シャドーパンチ': 'Shadow Punch',
			'じんつうりき': 'Extrasensory',
			'スカイアッパー': 'Sky Uppercut',
			'すなじごく': 'Sand Tomb',
			'ぜったいれいど': 'Sheer Cold',
			'だくりゅう': 'Muddy Water',
			'タネマシンガン': 'Bullet Seed',
			'つばめがえし': 'Aerial Ace',
			'つららばり': 'Icicle Spear',
			'てっぺき': 'Iron Defense',
			'とおぼえ': 'Howl',
			'ドラゴンクロー': 'Dragon Claw',
			'ハードプラント': 'Frenzy Plant',
			'ビルドアップ': 'Bulk Up',
			'とびはねる': 'Bounce',
			'マッドショット': 'Mud Shot',
			'ポイズンテール': 'Poison Tail',
			'ほしがる': 'Covet',
			'ボルテッカー': 'Volt Tackle',
			'マジカルリーフ': 'Magical Leaf',
			'みずあそび': 'Water Sport',
			'めいそう': 'Calm Mind',
			'リーフブレード': 'Leaf Blade',
			'りゅうのまい': 'Dragon Dance',
			'ロックブラスト': 'Rock Blast',
			'でんげきは': 'Shock Wave',
			'みずのはどう': 'Water Pulse',
			'はめつのねがい': 'Doom Desire',
			'サイコブースト': 'Psycho Boost',
			'はねやすめ': 'Roost',
			'じゅうりょく': 'Gravity',
			'ミラクルアイ': 'Miracle Eye',
			'めざましビンタ': 'Wake-Up Slap',
			'アームハンマー': 'Hammer Arm',
			'ジャイロボール': 'Gyro Ball',
			'いやしのねがい': 'Healing Wish',
			'しおみず': 'Brine',
			'しぜんのめぐみ': 'Natural Gift',
			'フェイント': 'Feint',
			'ついばむ': 'Pluck',
			'おいかぜ': 'Tailwind',
			'つぼをつく': 'Acupressure',
			'メタルバースト': 'Metal Burst',
			'とんぼがえり': 'U-turn',
			'インファイト': 'Close Combat',
			'しっぺがえし': 'Payback',
			'ダメおし': 'Assurance',
			'さしおさえ': 'Embargo',
			'なげつける': 'Fling',
			'サイコシフト': 'Psycho Shift',
			'きりふだ': 'Trump Card',
			'かいふくふうじ': 'Heal Block',
			'しぼりとる': 'Wring Out',
			'パワートリック': 'Power Trick',
			'いえき': 'Gastro Acid',
			'おまじない': 'Lucky Chant',
			'さきどり': 'Me First',
			'まねっこ': 'Copycat',
			'パワースワップ': 'Power Swap',
			'ガードスワップ': 'Guard Swap',
			'おしおき': 'Punishment',
			'とっておき': 'Last Resort',
			'なやみのタネ': 'Worry Seed',
			'ふいうち': 'Sucker Punch',
			'どくびし': 'Toxic Spikes',
			'ハートスワップ': 'Heart Swap',
			'アクアリング': 'Aqua Ring',
			'でんじふゆう': 'Magnet Rise',
			'フレアドライブ': 'Flare Blitz',
			'はっけい': 'Force Palm',
			'はどうだん': 'Aura Sphere',
			'ロックカット': 'Rock Polish',
			'どくづき': 'Poison Jab',
			'あくのはどう': 'Dark Pulse',
			'つじぎり': 'Night Slash',
			'アクアテール': 'Aqua Tail',
			'タネばくだん': 'Seed Bomb',
			'エアスラッシュ': 'Air Slash',
			'シザークロス': 'X-Scissor',
			'むしのさざめき': 'Bug Buzz',
			'りゅうのはどう': 'Dragon Pulse',
			'ドラゴンダイブ': 'Dragon Rush',
			'パワージェム': 'Power Gem',
			'ドレインパンチ': 'Drain Punch',
			'しんくうは': 'Vacuum Wave',
			'きあいだま': 'Focus Blast',
			'エナジーボール': 'Energy Ball',
			'ブレイブバード': 'Brave Bird',
			'だいちのちから': 'Earth Power',
			'すりかえ': 'Switcheroo',
			'ギガインパクト': 'Giga Impact',
			'わるだくみ': 'Nasty Plot',
			'バレットパンチ': 'Bullet Punch',
			'ゆきなだれ': 'Avalanche',
			'こおりのつぶて': 'Ice Shard',
			'シャドークロー': 'Shadow Claw',
			'かみなりのキバ': 'Thunder Fang',
			'こおりのキバ': 'Ice Fang',
			'ほのおのキバ': 'Fire Fang',
			'かげうち': 'Shadow Sneak',
			'どろばくだん': 'Mud Bomb',
			'サイコカッター': 'Psycho Cut',
			'しねんのずつき': 'Zen Headbutt',
			'ミラーショット': 'Mirror Shot',
			'ラスターカノン': 'Flash Cannon',
			'ロッククライム': 'Rock Climb',
			'きりばらい': 'Defog',
			'トリックルーム': 'Trick Room',
			'りゅうせいぐん': 'Draco Meteor',
			'ほうでん': 'Discharge',
			'ふんえん': 'Lava Plume',
			'リーフストーム': 'Leaf Storm',
			'パワーウィップ': 'Power Whip',
			'がんせきほう': 'Rock Wrecker',
			'クロスポイズン': 'Cross Poison',
			'ダストシュート': 'Gunk Shot',
			'アイアンヘッド': 'Iron Head',
			'マグネットボム': 'Magnet Bomb',
			'ストーンエッジ': 'Stone Edge',
			'ゆうわく': 'Captivate',
			'ステルスロック': 'Stealth Rock',
			'くさむすび': 'Grass Knot',
			'おしゃべり': 'Chatter',
			'さばきのつぶて': 'Judgment',
			'むしくい': 'Bug Bite',
			'チャージビーム': 'Charge Beam',
			'ウッドハンマー': 'Wood Hammer',
			'アクアジェット': 'Aqua Jet',
			'こうげきしれい': 'Attack Order',
			'ぼうぎょしれい': 'Defend Order',
			'かいふくしれい': 'Heal Order',
			'もろはのずつき': 'Head Smash',
			'ダブルアタック': 'Double Hit',
			'ときのほうこう': 'Roar of Time',
			'あくうせつだん': 'Spacial Rend',
			'みかづきのまい': 'Lunar Dance',
			'にぎりつぶす': 'Crush Grip',
			'マグマストーム': 'Magma Storm',
			'ダークホール': 'Dark Void',
			'シードフレア': 'Seed Flare',
			'あやしいかぜ': 'Ominous Wind',
			'シャドーダイブ': 'Shadow Force',
			'つめとぎ': 'Hone Claws',
			'ワイドガード': 'Wide Guard',
			'ガードシェア': 'Guard Split',
			'パワーシェア': 'Power Split',
			'ワンダールーム': 'Wonder Room',
			'サイコショック': 'Psyshock',
			'ベノムショック': 'Venoshock',
			'ボディパージ': 'Autotomize',
			'いかりのこな': 'Rage Powder',
			'テレキネシス': 'Telekinesis',
			'マジックルーム': 'Magic Room',
			'うちおとす': 'Smack Down',
			'やまあらし': 'Storm Throw',
			'はじけるほのお': 'Flame Burst',
			'ヘドロウェーブ': 'Sludge Wave',
			'ちょうのまい': 'Quiver Dance',
			'ヘビーボンバー': 'Heavy Slam',
			'シンクロノイズ': 'Synchronoise',
			'エレキボール': 'Electro Ball',
			'みずびたし': 'Soak',
			'ニトロチャージ': 'Flame Charge',
			'とぐろをまく': 'Coil',
			'ローキック': 'Low Sweep',
			'アシッドボム': 'Acid Spray',
			'イカサマ': 'Foul Play',
			'シンプルビーム': 'Simple Beam',
			'なかまづくり': 'Entrainment',
			'おさきにどうぞ': 'After You',
			'りんしょう': 'Round',
			'エコーボイス': 'Echoed Voice',
			'なしくずし': 'Chip Away',
			'クリアスモッグ': 'Clear Smog',
			'アシストパワー': 'Stored Power',
			'ファストガード': 'Quick Guard',
			'サイドチェンジ': 'Ally Switch',
			'ねっとう': 'Scald',
			'からをやぶる': 'Shell Smash',
			'いやしのはどう': 'Heal Pulse',
			'たたりめ': 'Hex',
			'フリーフォール': 'Sky Drop',
			'ギアチェンジ': 'Shift Gear',
			'ともえなげ': 'Circle Throw',
			'やきつくす': 'Incinerate',
			'さきおくり': 'Quash',
			'アクロバット': 'Acrobatics',
			'ミラータイプ': 'Reflect Type',
			'かたきうち': 'Retaliate',
			'いのちがけ': 'Final Gambit',
			'ギフトパス': 'Bestow',
			'れんごく': 'Inferno',
			'みずのちかい': 'Water Pledge',
			'ほのおのちかい': 'Fire Pledge',
			'くさのちかい': 'Grass Pledge',
			'ボルトチェンジ': 'Volt Switch',
			'むしのていこう': 'Struggle Bug',
			'じならし': 'Bulldoze',
			'こおりのいぶき': 'Frost Breath',
			'ドラゴンテール': 'Dragon Tail',
			'ふるいたてる': 'Work Up',
			'エレキネット': 'Electroweb',
			'ワイルドボルト': 'Wild Charge',
			'ドリルライナー': 'Drill Run',
			'ダブルチョップ': 'Dual Chop',
			'ハートスタンプ': 'Heart Stamp',
			'ウッドホーン': 'Horn Leech',
			'せいなるつるぎ': 'Sacred Sword',
			'シェルブレード': 'Razor Shell',
			'ヒートスタンプ': 'Heat Crash',
			'グラスミキサー': 'Leaf Tornado',
			'ハードローラー': 'Steamroller',
			'コットンガード': 'Cotton Guard',
			'ナイトバースト': 'Night Daze',
			'サイコブレイク': 'Psystrike',
			'スイープビンタ': 'Tail Slap',
			'ぼうふう': 'Hurricane',
			'アフロブレイク': 'Head Charge',
			'ギアソーサー': 'Gear Grind',
			'かえんだん': 'Searing Shot',
			'テクノバスター': 'Techno Blast',
			'いにしえのうた': 'Relic Song',
			'しんぴのつるぎ': 'Secret Sword',
			'こごえるせかい': 'Glaciate',
			'らいげき': 'Bolt Strike',
			'あおいほのお': 'Blue Flare',
			'ほのおのまい': 'Fiery Dance',
			'フリーズボルト': 'Freeze Shock',
			'コールドフレア': 'Ice Burn',
			'バークアウト': 'Snarl',
			'つららおとし': 'Icicle Crash',
			'Ｖジェネレート': 'V-create',
			'クロスフレイム': 'Fusion Flare',
			'クロスサンダー': 'Fusion Bolt',
			'フライングプレス': 'Flying Press',
			'たたみがえし': 'Mat Block',
			'ゲップ': 'Belch',
			'たがやす': 'Rototiller',
			'ねばねばネット': 'Sticky Web',
			'とどめばり': 'Fell Stinger',
			'ゴーストダイブ': 'Phantom Force',
			'ハロウィン': 'Trick-or-Treat',
			'おたけび': 'Noble Roar',
			'プラズマシャワー': 'Ion Deluge',
			'パラボラチャージ': 'Parabolic Charge',
			'もりののろい': 'Forest\'s Curse',
			'ねむる': 'Rest',
			'はなふぶき': 'Petal Blizzard',
			'ふぶき': 'Blizzard',
			'フリーズドライ': 'Freeze-Dry',
			'チャームボイス': 'Disarming Voice',
			'すてゼリフ': 'Parting Shot',
			'ひっくりかえす': 'Topsy-Turvy',
			'ドレインキッス': 'Draining Kiss',
			'トリックガード': 'Crafty Shield',
			'フラワーガード': 'Flower Shield',
			'グラスフィールド': 'Grassy Terrain',
			'ミストフィールド': 'Misty Terrain',
			'そうでん': 'Electrify',
			'じゃれつく': 'Play Rough',
			'ようせいのかぜ': 'Fairy Wind',
			'ムーンフォース': 'Moonblast',
			'ばくおんぱ': 'Boomburst',
			'フェアリーロック': 'Fairy Lock',
			'キングシールド': 'King\'s Shield',
			'なかよくする': 'Play Nice',
			'ないしょばなし': 'Confide',
			'ダイヤストーム': 'Diamond Storm',
			'スチームバースト': 'Steam Eruption',
			'いじげんホール': 'Hyperspace Hole',
			'みずしゅりけん': 'Water Shuriken',
			'マジカルフレイム': 'Mystical Fire',
			'ニードルガード': 'Spiky Shield',
			'アロマミスト': 'Aromatic Mist',
			'かいでんぱ': 'Eerie Impulse',
			'ベノムトラップ': 'Venom Drench',
			'ジオコントロール': 'Geomancy',
			'じばそうさ': 'Magnetic Flux',
			'ハッピータイム': 'Happy Hour',
			'エレキフィールド': 'Electric Terrain',
			'マジカルシャイン': 'Dazzling Gleam',
			'おいわい': 'Celebrate',
			'てをつなぐ': 'Hold Hands',
			'つぶらなひとみ': 'Baby-Doll Eyes',
			'ほっぺすりすり': 'Nuzzle',
			'てかげん': 'Hold Back',
			'まとわりつく': 'Infestation',
			'グロウパンチ': 'Power-Up Punch',
			'デスウイング': 'Oblivion Wing',
			'サウザンアロー': 'Thousand Arrows',
			'サウザンウェーブ': 'Thousand Waves',
			'グランドフォース': 'Land\'s Wrath',
			'はめつのひかり': 'Light of Ruin',
			'こんげんのはどう': 'Origin Pulse',
			'だんがいのつるぎ': 'Precipice Blades',
			'ガリョウテンセイ': 'Dragon Ascent',
			'いじげんラッシュ': 'Hyperspace Fury',
			'すなあつめ': 'Shore Up',
			'であいがしら': 'First Impression',
			'トーチカ': 'Baneful Bunker',
			'かげぬい': 'Spirit Shackle',
			'DDラリアト': 'Darkest Lariat',
			'うたかたのアリア': 'Sparkling Aria',
			'アイスハンマー': 'Ice Hammer',
			'フラワーヒール': 'Floral Healing',
			'10まんばりき': 'High Horsepower',
			'ちからをすいとる': 'Strength Sap',
			'ソーラーブレード': 'Solar Blade',
			'このは': 'Leafage',
			'スポットライト': 'Spotlight',
			'どくのいと': 'Toxic Thread',
			'とぎすます': 'Laser Focus',
			'アシストギア': 'Gear Up',
			'じごくづき': 'Throat Chop',
			'かふんだんご': 'Pollen Puff',
			'アンカーショット': 'Anchor Shot',
			'サイコフィールド': 'Psychic Terrain',
			'とびかかる': 'Lunge',
			'ほのおのムチ': 'Fire Lash',
			'つけあがる': 'Power Trip',
			'もえつきる': 'Burn Up',
			'スピードスワップ': 'Speed Swap',
			'スマートホーン': 'Smart Strike',
			'じょうか': 'Purify',
			'めざめるダンス': 'Revelation Dance',
			'コアパニッシャー': 'Core Enforcer',
			'トロピカルキック': 'Trop Kick',
			'さいはい': 'Instruct',
			'くちばしキャノン': 'Beak Blast',
			'スケイルノイズ': 'Clanging Scales',
			'ドラゴンハンマー': 'Dragon Hammer',
			'ぶんまわす': 'Brutal Swing',
			'オーロラベール': 'Aurora Veil',
			'トラップシェル': 'Shell Trap',
			'フルールカノン': 'Fleur Cannon',
			'サイコファング': 'Psychic Fangs',
			'じたんだ': 'Stomping Tantrum',
			'じだんだ': 'Stomping Tantrum',
			'シャドーボーン': 'Shadow Bone',
			'アクセルロック': 'Accelerock',
			'アクアブレイク': 'Liquidation',
			'プリズムレーザー': 'Prismatic Laser',
			'シャドースチール': 'Spectral Thief',
			'メテオドライブ': 'Sunsteel Strike',
			'シャドーレイ': 'Moongeist Beam',
			'なみだめ': 'Tearful Look',
			'びりびりちくちく': 'Zing Zap',
			'しぜんのいかり': 'Nature\'s Madness',
			'マルチアタック': 'Multi-Attack',
			'ビックリヘッド': 'Mind Blown',
			'プラズマフィスト': 'Plasma Fists',
			'フォトンゲイザー': 'Photon Geyser',
			'ウルトラダッシュアタック': 'Breakneck Blitz',
			'全力無双激烈拳': 'All-Out Pummeling',
			'ファイナルダイブクラッシュ': 'Supersonic Skystrike',
			'アシッドポイズンデリート': 'Acid Downpour',
			'ライジングランドオーバー': 'Tectonic Rage',
			'ワールドエンドフォール': 'Continental Crush',
			'絶対捕食回転斬': 'Savage Spin-Out',
			'無限暗夜への誘い': 'Never-Ending Nightmare',
			'超絶螺旋連撃': 'Corkscrew Crash',
			'ダイナミックフルフレイム': 'Inferno Overdrive',
			'スーパーアクアトルネード': 'Hydro Vortex',
			'ブルームシャインエクストラ': 'Bloom Doom',
			'スパーキングギガボルト': 'Gigavolt Havoc',
			'マキシマムサイブレイカー': 'Shattered Psyche',
			'レイジングジオフリーズ': 'Subzero Slammer',
			'アルティメットドラゴンバーン': 'Devastating Drake',
			'ブラックホールイクリプス': 'Black Hole Eclipse',
			'ラブリースターインパクト': 'Twinkle Tackle',
			'ひっさつのピカチュート': 'Catastropika',
			'シャドーアローズストライク': 'Sinister Arrow Raid',
			'ハイパーダーククラッシャー': 'Malicious Moonsault',
			'わだつみのシンフォニア': 'Oceanic Operetta',
			'ガーディアン・デ・アローラ': 'Guardian of Alola',
			'七星奪魂腿': 'Soul-Stealing 7-Star Strike',
			'ライトニングサーフライド': 'Stoked Sparksurfer',
			'ほんきをだすこうげき': 'Pulverizing Pancake',
			'ナインエボルブースト': 'Extreme Evoboost',
			'オリジンズスーパーノヴァ': 'Genesis Supernova',
			'1000まんボルト': '10,000,000 Volt Thunderbolt',
			'天焦がす滅亡の光': 'Light That Burns the Sky',
			'サンシャインスマッシャー': 'Searing Sunraze Smash',
			'ムーンライトブラスター': 'Menacing Moonraze Maelstrom',
			'ぽかぼかフレンドタイム': 'Let\'s Snuggle Forever',
			'ラジアルエッジストーム': 'Splintered Stormshards',
			'ブレイジングソウルビート': 'Clangorous Soulblaze',
			'めざめるパワー': 'Hidden Power ',
			'いかり': 'Rage',
			'とおせんぼう': 'Block',
			'トリック': 'Trick',
			'あくしゅう': 'Stench',
			'あめふらし': 'Drizzle',
			'かそく': 'Speed Boost',
			'カブトアーマー': 'Battle Armor',
			'がんじょう': 'Sturdy',
			'しめりけ': 'Damp',
			'じゅうなん': 'Limber',
			'すながくれ': 'Sand Veil',
			'せいでんき': 'Static',
			'ちくでん': 'Volt Absorb',
			'ちょすい': 'Water Absorb',
			'どんかん': 'Oblivious',
			'ノーてんき': 'Cloud Nine',
			'ふくがん': 'Compound Eyes',
			'ふみん': 'Insomnia',
			'へんしょく': 'Color Change',
			'めんえき': 'Immunity',
			'もらいび': 'Flash Fire',
			'りんぷん': 'Shield Dust',
			'マイペース': 'Own Tempo',
			'きゅうばん': 'Suction Cups',
			'いかく': 'Intimidate',
			'かげふみ': 'Shadow Tag',
			'さめはだ': 'Rough Skin',
			'ふしぎなまもり': 'Wonder Guard',
			'ふゆう': 'Levitate',
			'ほうし': 'Effect Spore',
			'シンクロ': 'Synchronize',
			'クリアボディ': 'Clear Body',
			'しぜんかいふく': 'Natural Cure',
			'ひらいしん': 'Lightning Rod',
			'てんのめぐみ': 'Serene Grace',
			'すいすい': 'Swift Swim',
			'ようりょくそ': 'Chlorophyll',
			'はっこう': 'Illuminate',
			'トレース': 'Trace',
			'ちからもち': 'Huge Power',
			'どくのトゲ': 'Poison Point',
			'せいしんりょく': 'Inner Focus',
			'マグマのよろい': 'Magma Armor',
			'みずのベール': 'Water Veil',
			'じりょく': 'Magnet Pull',
			'ぼうおん': 'Soundproof',
			'あめうけざら': 'Rain Dish',
			'すなおこし': 'Sand Stream',
			'プレッシャー': 'Pressure',
			'あついしぼう': 'Thick Fat',
			'はやおき': 'Early Bird',
			'ほのおのからだ': 'Flame Body',
			'にげあし': 'Run Away',
			'するどいめ': 'Keen Eye',
			'かいりきバサミ': 'Hyper Cutter',
			'ものひろい': 'Pickup',
			'なまけ': 'Truant',
			'はりきり': 'Hustle',
			'メロメロボディ': 'Cute Charm',
			'プラス': 'Plus',
			'マイナス': 'Minus',
			'てんきや': 'Forecast',
			'ねんちゃく': 'Sticky Hold',
			'だっぴ': 'Shed Skin',
			'こんじょう': 'Guts',
			'ふしぎなうろこ': 'Marvel Scale',
			'ヘドロえき': 'Liquid Ooze',
			'しんりょく': 'Overgrow',
			'もうか': 'Blaze',
			'げきりゅう': 'Torrent',
			'むしのしらせ': 'Swarm',
			'いしあたま': 'Rock Head',
			'ひでり': 'Drought',
			'ありじごく': 'Arena Trap',
			'やるき': 'Vital Spirit',
			'しろいけむり': 'White Smoke',
			'ヨガパワー': 'Pure Power',
			'シェルアーマー': 'Shell Armor',
			'エアロック': 'Air Lock',
			'ちどりあし': 'Tangled Feet',
			'でんきエンジン': 'Motor Drive',
			'とうそうしん': 'Rivalry',
			'ふくつのこころ': 'Steadfast',
			'ゆきがくれ': 'Snow Cloak',
			'くいしんぼう': 'Gluttony',
			'いかりのつぼ': 'Anger Point',
			'かるわざ': 'Unburden',
			'たいねつ': 'Heatproof',
			'たんじゅん': 'Simple',
			'かんそうはだ': 'Dry Skin',
			'ダウンロード': 'Download',
			'てつのこぶし': 'Iron Fist',
			'ポイズンヒール': 'Poison Heal',
			'てきおうりょく': 'Adaptability',
			'スキルリンク': 'Skill Link',
			'うるおいボディ': 'Hydration',
			'サンパワー': 'Solar Power',
			'はやあし': 'Quick Feet',
			'ノーマルスキン': 'Normalize',
			'スナイパー': 'Sniper',
			'マジックガード': 'Magic Guard',
			'ノーガード': 'No Guard',
			'あとだし': 'Stall',
			'テクニシャン': 'Technician',
			'リーフガード': 'Leaf Guard',
			'ぶきよう': 'Klutz',
			'かたやぶり': 'Mold Breaker',
			'きょううん': 'Super Luck',
			'ゆうばく': 'Aftermath',
			'きけんよち': 'Anticipation',
			'よちむ': 'Forewarn',
			'てんねん': 'Unaware',
			'いろめがね': 'Tinted Lens',
			'フィルター': 'Filter',
			'スロースタート': 'Slow Start',
			'きもったま': 'Scrappy',
			'よびみず': 'Storm Drain',
			'アイスボディ': 'Ice Body',
			'ハードロック': 'Solid Rock',
			'ゆきふらし': 'Snow Warning',
			'みつあつめ': 'Honey Gather',
			'おみとおし': 'Frisk',
			'すてみ': 'Reckless',
			'マルチタイプ': 'Multitype',
			'フラワーギフト': 'Flower Gift',
			'ナイトメア': 'Bad Dreams',
			'わるいてぐせ': 'Pickpocket',
			'ちからずく': 'Sheer Force',
			'あまのじゃく': 'Contrary',
			'きんちょうかん': 'Unnerve',
			'まけんき': 'Defiant',
			'よわき': 'Defeatist',
			'のろわれボディ': 'Cursed Body',
			'いやしのこころ': 'Healer',
			'フレンドガード': 'Friend Guard',
			'くだけるよろい': 'Weak Armor',
			'ヘヴィメタル': 'Heavy Metal',
			'ライトメタル': 'Light Metal',
			'マルチスケイル': 'Multiscale',
			'どくぼうそう': 'Toxic Boost',
			'ねつぼうそう': 'Flare Boost',
			'しゅうかく': 'Harvest',
			'テレパシー': 'Telepathy',
			'ムラっけ': 'Moody',
			'ぼうじん': 'Overcoat',
			'どくしゅ': 'Poison Touch',
			'さいせいりょく': 'Regenerator',
			'はとむね': 'Big Pecks',
			'すなかき': 'Sand Rush',
			'ミラクルスキン': 'Wonder Skin',
			'アナライズ': 'Analytic',
			'イリュージョン': 'Illusion',
			'かわりもの': 'Imposter',
			'すりぬけ': 'Infiltrator',
			'ミイラ': 'Mummy',
			'じしんかじょう': 'Moxie',
			'せいぎのこころ': 'Justified',
			'びびり': 'Rattled',
			'マジックミラー': 'Magic Bounce',
			'そうしょく': 'Sap Sipper',
			'いたずらごころ': 'Prankster',
			'すなのちから': 'Sand Force',
			'てつのトゲ': 'Iron Barbs',
			'ダルマモード': 'Zen Mode',
			'しょうりのほし': 'Victory Star',
			'ターボブレイズ': 'Turboblaze',
			'テラボルテージ': 'Teravolt',
			'アロマベール': 'Aroma Veil',
			'フラワーベール': 'Flower Veil',
			'ほおぶくろ': 'Cheek Pouch',
			'へんげんじざい': 'Protean',
			'ファーコート': 'Fur Coat',
			'マジシャン': 'Magician',
			'ぼうだん': 'Bulletproof',
			'かちき': 'Competitive',
			'がんじょうあご': 'Strong Jaw',
			'フリーズスキン': 'Refrigerate',
			'スイートベール': 'Sweet Veil',
			'バトルスイッチ': 'Stance Change',
			'はやてのつばさ': 'Gale Wings',
			'メガランチャー': 'Mega Launcher',
			'くさのけがわ': 'Grass Pelt',
			'きょうせい': 'Symbiosis',
			'かたいツメ': 'Tough Claws',
			'フェアリースキン': 'Pixilate',
			'ぬめぬめ': 'Gooey',
			'スカイスキン': 'Aerilate',
			'おやこあい': 'Parental Bond',
			'ダークオーラ': 'Dark Aura',
			'フェアリーオーラ': 'Fairy Aura',
			'オーラブレイク': 'Aura Break',
			'はじまりのうみ': 'Primordial Sea',
			'おわりのだいち': 'Desolate Land',
			'デルタストリーム': 'Delta Stream',
			'じきゅうりょく': 'Stamina',
			'にげごし': 'Wimp Out',
			'ききかいひ': 'Emergency Exit',
			'みずがため': 'Water Compaction',
			'ひとでなし': 'Merciless',
			'リミットシールド': 'Shields Down',
			'はりこみ': 'Stakeout',
			'すいほう': 'Water Bubble',
			'はがねつかい': 'Steelworker',
			'ぎゃくじょう': 'Berserk',
			'ゆきかき': 'Slush Rush',
			'えんかく': 'Long Reach',
			'うるおいボイス': 'Liquid Voice',
			'ヒーリングシフト': 'Triage',
			'エレキスキン': 'Galvanize',
			'サーフテール': 'Surge Surfer',
			'ぎょぐん': 'Schooling',
			'ばけのかわ': 'Disguise',
			'きずなへんげ': 'Battle Bond',
			'スワームチェンジ': 'Power Construct',
			'ふしょく': 'Corrosion',
			'ぜったいねむり': 'Comatose',
			'じょおうのいげん': 'Queenly Majesty',
			'とびだすなかみ': 'Innards Out',
			'おどりこ': 'Dancer',
			'バッテリー': 'Battery',
			'もふもふ': 'Fluffy',
			'ビビッドボディ': 'Dazzling',
			'ソウルハート': 'Soul-Heart',
			'カーリーヘアー': 'Tangling Hair',
			'レシーバー': 'Receiver',
			'かがくのちから': 'Power of Alchemy',
			'ビーストブースト': 'Beast Boost',
			'ＡＲシステム': 'RKS System',
			'エレキメイカー': 'Electric Surge',
			'サイコメイカー': 'Psychic Surge',
			'ミストメイカー': 'Misty Surge',
			'グラスメイカー': 'Grassy Surge',
			'メタルプロテクト': 'Full Metal Body',
			'ファントムガード': 'Shadow Shield',
			'プリズムアーマー': 'Prism Armor',
			'ブレインフォース': 'Neuroforce',

			// ITEMS

			'ひかりのこな': 'Bright Powder',
			'せんせいのツメ': 'Quick Claw',
			'おうじゃのしるし': 'King\'s Rock',
			'ぎんのこな': 'Silver Powder',
			'おまもりこばん': 'Amulet Coin',
			'きよめのおふだ': 'Cleanse Tag',
			'けむりだま': 'Smoke Ball',
			'かわらずのいし': 'Everstone',
			'きあいのハチマキ': 'Focus Band',
			'しあわせタマゴ': 'Lucky Egg',
			'ピントレンズ': 'Scope Lens',
			'メタルコート': 'Metal Coat',
			'たべのこし': 'Leftovers',
			'りゅうのウロコ': 'Dragon Scale',
			'でんきだま': 'Light Ball',
			'やわらかいすな': 'Soft Sand',
			'かたいいし': 'Hard Stone',
			'きせきのタネ': 'Miracle Seed',
			'くろいメガネ': 'Black Glasses',
			'くろおび': 'Black Belt',
			'じしゃく': 'Magnet',
			'しんぴのしずく': 'Mystic Water',
			'するどいくちばし': 'Sharp Beak',
			'どくバリ': 'Poison Barb',
			'とけないこおり': 'Never-Melt Ice',
			'のろいのおふだ': 'Spell Tag',
			'まがったスプーン': 'Twisted Spoon',
			'もくたん': 'Charcoal',
			'りゅうのキバ': 'Dragon Fang',
			'ピンクのリボン': 'Pink Bow',
			'みずたまりボン': 'Polkadot Bow',
			'アップグレード': 'Up-Grade',
			'ラッキーパンチ': 'Lucky Punch',
			'メタルパウダー': 'Metal Powder',
			'ふといホネ': 'Thick Club',
			'ながねぎ': 'Stick',
			'はかいのいでんし': 'Berserk Gene',
			'しろいハーブ': 'White Herb',
			'きょうせいギプス': 'Macho Brace',
			'やすらぎのすず': 'Soothe Bell',
			'メンタルハーブ': 'Mental Herb',
			'こだわりハチマキ': 'Choice Band',
			'こころのしずく': 'Soul Dew',
			'しんかいのキバ': 'Deep Sea Tooth',
			'しんかいのウロコ': 'Deep Sea Scale',
			'シルクのスカーフ': 'Silk Scarf',
			'かいがらのすず': 'Shell Bell',
			'うしおのおこう': 'Sea Incense',
			'のんきのおこう': 'Lax Incense',
			'あかいバンダナ': 'Red Scarf',
			'あおいバンダナ': 'Blue Scarf',
			'ピンクのバンダナ': 'Pink Scarf',
			'みどりのバンダナ': 'Green Scarf',
			'きいろのバンダナ': 'Yellow Scarf',
			'べにいろのたま': 'Red Orb',
			'あいいろのたま': 'Blue Orb',
			'ひのたまプレート': 'Flame Plate',
			'しずくプレート': 'Splash Plate',
			'いかずちプレート': 'Zap Plate',
			'みどりのプレート': 'Meadow Plate',
			'つららのプレート': 'Icicle Plate',
			'こぶしのプレート': 'Fist Plate',
			'もうどくプレート': 'Toxic Plate',
			'だいちのプレート': 'Earth Plate',
			'あおぞらプレート': 'Sky Plate',
			'ふしぎのプレート': 'Mind Plate',
			'たまむしプレート': 'Insect Plate',
			'がんせきプレート': 'Stone Plate',
			'もののけプレート': 'Spooky Plate',
			'りゅうのプレート': 'Draco Plate',
			'こわもてプレート': 'Dread Plate',
			'こうてつプレート': 'Iron Plate',
			'あやしいおこう': 'Odd Incense',
			'がんせきおこう': 'Rock Incense',
			'まんぷくおこう': 'Full Incense',
			'さざなみのおこう': 'Wave Incense',
			'おはなのおこう': 'Rose Incense',
			'こううんのおこう': 'Luck Incense',
			'きよめのおこう': 'Pure Incense',
			'プロテクター': 'Protector',
			'エレキブースター': 'Electirizer',
			'マグマブースター': 'Magmarizer',
			'あやしいパッチ': 'Dubious Disc',
			'れいかいのぬの': 'Reaper Cloth',
			'するどいツメ': 'Razor Claw',
			'するどいキバ': 'Razor Fang',
			'まんまるいし': 'Oval Stone',
			'こんごうだま': 'Adamant Orb',
			'しらたま': 'Lustrous Orb',
			'はっきんだま': 'Griseous Orb',
			'こうかくレンズ': 'Wide Lens',
			'ちからのハチマキ': 'Muscle Band',
			'ものしりメガネ': 'Wise Glasses',
			'たつじんのおび': 'Expert Belt',
			'ひかりのねんど': 'Light Clay',
			'いのちのたま': 'Life Orb',
			'パワフルハーブ': 'Power Herb',
			'どくどくだま': 'Toxic Orb',
			'かえんだま': 'Flame Orb',
			'スピードパウダー': 'Quick Powder',
			'きあいのタスキ': 'Focus Sash',
			'フォーカスレンズ': 'Zoom Lens',
			'メトロノーム': 'Metronome',
			'くろいてっきゅう': 'Iron Ball',
			'こうこうのしっぽ': 'Lagging Tail',
			'あかいいと': 'Destiny Knot',
			'くろいヘドロ': 'Black Sludge',
			'つめたいいわ': 'Icy Rock',
			'さらさらいわ': 'Smooth Rock',
			'あついいわ': 'Heat Rock',
			'しめったいわ': 'Damp Rock',
			'ねばりのかぎづめ': 'Grip Claw',
			'こだわりスカーフ': 'Choice Scarf',
			'くっつきバリ': 'Sticky Barb',
			'パワーリスト': 'Power Bracer',
			'パワーベルト': 'Power Belt',
			'パワーレンズ': 'Power Lens',
			'パワーバンド': 'Power Band',
			'パワーアンクル': 'Power Anklet',
			'パワーウエイト': 'Power Weight',
			'きれいなぬけがら': 'Shed Shell',
			'おおきなねっこ': 'Big Root',
			'こだわりメガネ': 'Choice Specs',
			'アクアカセット': 'Douse Drive',
			'イナズマカセット': 'Shock Drive',
			'ブレイズカセット': 'Burn Drive',
			'フリーズカセット': 'Chill Drive',
			'きれいなウロコ': 'Prism Scale',
			'しんかのきせき': 'Eviolite',
			'かるいし': 'Float Stone',
			'ゴツゴツメット': 'Rocky Helmet',
			'ふうせん': 'Air Balloon',
			'レッドカード': 'Red Card',
			'ねらいのまと': 'Ring Target',
			'しめつけバンド': 'Binding Band',
			'きゅうこん': 'Absorb Bulb',
			'じゅうでんち': 'Cell Battery',
			'だっしゅつボタン': 'Eject Button',
			'ほのおのジュエル': 'Fire Gem',
			'みずのジュエル': 'Water Gem',
			'でんきのジュエル': 'Electric Gem',
			'くさのジュエル': 'Grass Gem',
			'こおりのジュエル': 'Ice Gem',
			'かくとうジュエル': 'Fighting Gem',
			'どくのジュエル': 'Poison Gem',
			'じめんのジュエル': 'Ground Gem',
			'ひこうのジュエル': 'Flying Gem',
			'エスパージュエル': 'Psychic Gem',
			'むしのジュエル': 'Bug Gem',
			'いわのジュエル': 'Rock Gem',
			'ゴーストジュエル': 'Ghost Gem',
			'ドラゴンジュエル': 'Dragon Gem',
			'あくのジュエル': 'Dark Gem',
			'はがねのジュエル': 'Steel Gem',
			'ノーマルジュエル': 'Normal Gem',
			'フェアリージュエル': 'Fairy Gem',
			'じゃくてんほけん': 'Weakness Policy',
			'とつげきチョッキ': 'Assault Vest',
			'せいれいプレート': 'Pixie Plate',
			'ホイップポップ': 'Whipped Dream',
			'においぶくろ': 'Sachet',
			'ひかりごけ': 'Luminous Moss',
			'ゆきだま': 'Snowball',
			'ぼうじんゴーグル': 'Safety Goggles',
			'ゲンガナイト': 'Gengarite',
			'サーナイトナイト': 'Gardevoirite',
			'デンリュウナイト': 'Ampharosite',
			'フシギバナイト': 'Venusaurite',
			'リザードナイトX': 'Charizardite X',
			'カメックスナイト': 'Blastoisinite',
			'ミュウツナイトX': 'Mewtwonite X',
			'ミュウツナイトY': 'Mewtwonite Y',
			'バシャーモナイト': 'Blazikenite',
			'チャーレムナイト': 'Medichamite',
			'ヘルガナイト': 'Houndoominite',
			'ボスゴドラナイト': 'Aggronite',
			'ジュペッタナイト': 'Banettite',
			'バンギラスナイト': 'Tyranitarite',
			'ハッサムナイト': 'Scizorite',
			'カイロスナイト': 'Pinsirite',
			'プテラナイト': 'Aerodactylite',
			'ルカリオナイト': 'Lucarionite',
			'ユキノオナイト': 'Abomasite',
			'ガルーラナイト': 'Kangaskhanite',
			'ギャラドスナイト': 'Gyaradosite',
			'アブソルナイト': 'Absolite',
			'リザードナイトY': 'Charizardite Y',
			'フーディナイト': 'Alakazite',
			'ヘラクロスナイト': 'Heracronite',
			'クチートナイト': 'Mawilite',
			'ライボルトナイト': 'Manectite',
			'ガブリアスナイト': 'Garchompite',
			'ラティアスナイト': 'Latiasite',
			'ラティオスナイト': 'Latiosite',
			'ラグラージナイト': 'Swampertite',
			'ジュカインナイト': 'Sceptilite',
			'ヤミラミナイト': 'Sablenite',
			'チルタリスナイト': 'Altarianite',
			'エルレイドナイト': 'Galladite',
			'タブンネナイト': 'Audinite',
			'メタグロスナイト': 'Metagrossite',
			'サメハダナイト': 'Sharpedonite',
			'ヤドランナイト': 'Slowbronite',
			'ハガネールナイト': 'Steelixite',
			'ピジョットナイト': 'Pidgeotite',
			'オニゴーリナイト': 'Glalitite',
			'ディアンシナイト': 'Diancite',
			'バクーダナイト': 'Cameruptite',
			'ミミロップナイト': 'Lopunnite',
			'ボーマンダナイト': 'Salamencite',
			'スピアナイト': 'Beedrillite',
			'ノーマルZ': 'Normalium Z',
			'ホノオZ': 'Firium Z',
			'ミズZ': 'Waterium Z',
			'デンキZ': 'Electrium Z',
			'クサZ': 'Grassium Z',
			'コオリZ': 'Icium Z',
			'カクトウZ': 'Fightinium Z',
			'ドクZ': 'Poisonium Z',
			'ジメンZ': 'Groundium Z',
			'ヒコウZ': 'Flyinium Z',
			'エスパーZ': 'Psychium Z',
			'ムシZ': 'Buginium Z',
			'イワZ': 'Rockium Z',
			'ゴーストZ': 'Ghostium Z',
			'ドラゴンZ': 'Dragonium Z',
			'アクZ': 'Darkinium Z',
			'ハガネZ': 'Steelium Z',
			'フェアリーZ': 'Fairium Z',
			'ピカチュウZ': 'Pikanium Z',
			'ジュナイパーZ': 'Decidium Z',
			'ガオガエンZ': 'Incinium Z',
			'アシレーヌZ': 'Primarium Z',
			'カプZ': 'Tapunium Z',
			'マーシャドーZ': 'Marshadium Z',
			'アロライZ': 'Aloraichium Z',
			'カビゴンZ': 'Snorlium Z',
			'イーブイZ': 'Eevium Z',
			'ミュウZ': 'Mewnium Z',
			'サトピカZ': 'Pikashunium Z',
			'ビビリだま': 'Adrenaline Orb',
			'グランドコート': 'Terrain Extender',
			'ぼうごパット': 'Protective Pads',
			'エレキシード': 'Electric Seed',
			'サイコシード': 'Psychic Seed',
			'ミストシード': 'Misty Seed',
			'グラスシード': 'Grassy Seed',
			'ファイトメモリ': 'Fighting Memory',
			'フライングメモリ': 'Flying Memory',
			'ポイズンメモリ': 'Poison Memory',
			'グラウンドメモリ': 'Ground Memory',
			'ロックメモリ': 'Rock Memory',
			'バグメモリ': 'Bug Memory',
			'ゴーストメモリ': 'Ghost Memory',
			'スチールメモリ': 'Steel Memory',
			'ファイヤーメモリ': 'Fire Memory',
			'ウオーターメモリ': 'Water Memory',
			'グラスメモリ': 'Grass Memory',
			'エレクトロメモリ': 'Electric Memory',
			'サイキックメモリ': 'Psychic Memory',
			'アイスメモリ': 'Ice Memory',
			'ドラゴンメモリ': 'Dragon Memory',
			'ダークメモリ': 'Dark Memory',
			'フェアリーメモリ': 'Fairy Memory',
			'ソルガレオZ': 'Solganium Z',
			'ルナアーラZ': 'Lunalium Z',
			'ウルトラネクロZ': 'Ultranecrozium Z',
			'ミミッキュZ': 'Mimikium Z',
			'ルガルガンZ': 'Lycanium Z',
			'ジャラランガZ': 'Kommonium Z',
			'ふんじん': 'Powder', // because of Brightpowder etc.

			// NATURES

			'さみしがり': 'Lonely',
			'ゆうかん': 'Brave',
			'いじっぱり': 'Adamant',
			'やんちゃ': 'Naughty',
			'ずぶとい': 'Bold',
			'すなお': 'Docile',
			'のんき': 'Relaxed',
			'わんぱく': 'Impish',
			'のうてんき': 'Lax',
			'おくびょう': 'Timid',
			'せっかち': 'Hasty',
			'まじめ': 'Serious',
			'ようき': 'Jolly',
			'むじゃき': 'Naive',
			'ひかえめ': 'Modest',
			'おっとり': 'Mild',
			'れいせい': 'Quiet',
			'てれや': 'Bashful',
			'うっかりや': 'Rash',
			'おだやか': 'Calm',
			'おとなしい': 'Gentle',
			'なまいき': 'Sassy',
			'しんちょう': 'Careful',
			'きまぐれ': 'Quirky',

			// POKEMON

			'フシギダネ': 'Bulbasaur',
			'フシギソウ': 'Ivysaur',
			'フシギバナ': 'Venusaur',
			'ヒトカゲ': 'Charmander',
			'リザードン': 'Charizard',
			'リザード': 'Charmeleon',
			'ゼニガメ': 'Squirtle',
			'カメール': 'Wartortle',
			'カメックス': 'Blastoise',
			'キャタピー': 'Caterpie',
			'トランセル': 'Metapod',
			'バタフリー': 'Butterfree',
			'ビードル': 'Weedle',
			'コクーン': 'Kakuna',
			'スピアー': 'Beedrill',
			'ポッポ': 'Pidgey',
			'ピジョン': 'Pidgeotto',
			'ピジョット': 'Pidgeot',
			'コラッタ': 'Rattata',
			'ラッタ': 'Raticate',
			'オニスズメ': 'Spearow',
			'オニドリル': 'Fearow',
			'アーボ': 'Ekans',
			'アーボック': 'Arbok',
			'ピカチュウ': 'Pikachu',
			'ライチュウ': 'Raichu',
			'サンド': 'Sandshrew',
			'サンドパン': 'Sandslash',
			'ニドラン♀': 'Nidoran♀',
			'ニドリーナ': 'Nidorina',
			'ニドクイン': 'Nidoqueen',
			'ニドラン♂': 'Nidoran♂',
			'ニドリーノ': 'Nidorino',
			'ニドキング': 'Nidoking',
			'ピッピ': 'Clefairy',
			'ピクシー': 'Clefable',
			'ロコン': 'Vulpix',
			'キュウコン': 'Ninetales',
			'プリン': 'Jigglypuff',
			'プクリン': 'Wigglytuff',
			'ズバット': 'Zubat',
			'ゴルバット': 'Golbat',
			'ナゾノGrassium': 'Oddish',
			'クサイハナ': 'Gloom',
			'ラフレシア': 'Vileplume',
			'パラス': 'Paras',
			'パラセクト': 'Parasect',
			'コンパン': 'Venonat',
			'モルフォン': 'Venomoth',
			'ディグダ': 'Diglett',
			'ダグトリオ': 'Dugtrio',
			'ニャース': 'Meowth',
			'ペルシアン': 'Persian',
			'コダック': 'Psyduck',
			'ゴルダック': 'Golduck',
			'マンキー': 'Mankey',
			'オコリザル': 'Primeape',
			'ガーディ': 'Growlithe',
			'ウインディ': 'Arcanine',
			'ニョロモ': 'Poliwag',
			'ニョロゾ': 'Poliwhirl',
			'ニョロボン': 'Poliwrath',
			'ケーシィ': 'Abra',
			'ユンゲラー': 'Kadabra',
			'フーディン': 'Alakazam',
			'ワンリキー': 'Machop',
			'ゴーリキー': 'Machoke',
			'カイリキー': 'Machamp',
			'マダツボミ': 'Bellsprout',
			'ウツドン': 'Weepinbell',
			'ウツボット': 'Victreebel',
			'メノクラゲ': 'Tentacool',
			'ドククラゲ': 'Tentacruel',
			'イシツブテ': 'Geodude',
			'ゴローン': 'Graveler',
			'ゴローニャ': 'Golem',
			'ポニータ': 'Ponyta',
			'ギャロップ': 'Rapidash',
			'ヤドン': 'Slowpoke',
			'ヤドラン': 'Slowbro',
			'コイル': 'Magnemite',
			'レアコイル': 'Magneton',
			'カモネギ': 'Farfetch\'d',
			'ドードー': 'Doduo',
			'ドードリオ': 'Dodrio',
			'パウワウ': 'Seel',
			'ジュゴン': 'Dewgong',
			'ベトベター': 'Grimer',
			'ベトベトン': 'Muk',
			'シェルダー': 'Shellder',
			'パルシェン': 'Cloyster',
			'ゴース': 'Gastly',
			'ゴースト': 'Haunter',
			'ゲンガー': 'Gengar',
			'Rockiumーク': 'Onix',
			'スリープ': 'Drowzee',
			'スリーパー': 'Hypno',
			'クラブ': 'Krabby',
			'キングラー': 'Kingler',
			'ビリリダマ': 'Voltorb',
			'マルマイン': 'Electrode',
			'タマタマ': 'Exeggcute',
			'ナッシー': 'Exeggutor',
			'カラカラ': 'Cubone',
			'ガラガラ': 'Marowak',
			'サワムラー': 'Hitmonlee',
			'エビワラー': 'Hitmonchan',
			'ベロリンガ': 'Lickitung',
			'ドガース': 'Koffing',
			'マタドガス': 'Weezing',
			'サイホーン': 'Rhyhorn',
			'サイドン': 'Rhydon',
			'ラッキー': 'Chansey',
			'モンジャラ': 'Tangela',
			'ガルーラ': 'Kangaskhan',
			'タッツー': 'Horsea',
			'シードラ': 'Seadra',
			'トサキント': 'Goldeen',
			'アズマオウ': 'Seaking',
			'ヒトデマン': 'Staryu',
			'スターミー': 'Starmie',
			'バリヤード': 'Mr. Mime',
			'ストライク': 'Scyther',
			'ルージュラ': 'Jynx',
			'エレブー': 'Electabuzz',
			'ブーバー': 'Magmar',
			'カイロス': 'Pinsir',
			'ケンタロス': 'Tauros',
			'コイキング': 'Magikarp',
			'ギャラドス': 'Gyarados',
			'ラプラス': 'Lapras',
			'メタモン': 'Ditto',
			'イーブイ': 'Eevee',
			'シャワーズ': 'Vaporeon',
			'サンダース': 'Jolteon',
			'ブースター': 'Flareon',
			'ポリゴン': 'Porygon',
			'オムナイト': 'Omanyte',
			'オムスター': 'Omastar',
			'カブト': 'Kabuto',
			'カブトプス': 'Kabutops',
			'プテラ': 'Aerodactyl',
			'カビゴン': 'Snorlax',
			'フリーザー': 'Articuno',
			'サンダー': 'Zapdos',
			'ファイヤー': 'Moltres',
			'ミニリュウ': 'Dratini',
			'ハクリュー': 'Dragonair',
			'カイリュー': 'Dragonite',
			'ミュウツー': 'Mewtwo',
			'ミュウ': 'Mew',
			'チコリータ': 'Chikorita',
			'ベイリーフ': 'Bayleef',
			'メガニウム': 'Meganium',
			'ヒノアラシ': 'Cyndaquil',
			'マグマラシ': 'Quilava',
			'バクフーン': 'Typhlosion',
			'ワニノコ': 'Totodile',
			'アリゲイツ': 'Croconaw',
			'オーダイル': 'Feraligatr',
			'オタチ': 'Sentret',
			'オオタチ': 'Furret',
			'ホーホー': 'Hoothoot',
			'ヨルノズク': 'Noctowl',
			'レディバ': 'Ledyba',
			'レディアン': 'Ledian',
			'イトマル': 'Spinarak',
			'アリアドス': 'Ariados',
			'クロバット': 'Crobat',
			'チョンチー': 'Chinchou',
			'ランターン': 'Lanturn',
			'ピチュー': 'Pichu',
			'ピィ': 'Cleffa',
			'ププリン': 'Igglybuff',
			'トゲピー': 'Togepi',
			'トゲチック': 'Togetic',
			'ネイティ': 'Natu',
			'ネイティオ': 'Xatu',
			'メリープ': 'Mareep',
			'モココ': 'Flaaffy',
			'デンリュウ': 'Ampharos',
			'キレイハナ': 'Bellossom',
			'マリルリ': 'Azumarill',
			'マリル': 'Marill',
			'ウソッキー': 'Sudowoodo',
			'ニョロトノ': 'Politoed',
			'ハネッコ': 'Hoppip',
			'ポポッコ': 'Skiploom',
			'ワタッコ': 'Jumpluff',
			'エイパム': 'Aipom',
			'ヒマナッツ': 'Sunkern',
			'キマワリ': 'Sunflora',
			'ヤンヤンマ': 'Yanma',
			'ウパー': 'Wooper',
			'ヌオー': 'Quagsire',
			'エーフィ': 'Espeon',
			'ブラッキー': 'Umbreon',
			'ヤミカラス': 'Murkrow',
			'ヤドキング': 'Slowking',
			'ムウマ': 'Misdreavus',
			'アンノーン': 'Unown',
			'ソーナンス': 'Wobbuffet',
			'キリンリキ': 'Girafarig',
			'クヌギダマ': 'Pineco',
			'フォレトス': 'Forretress',
			'ノコッチ': 'Dunsparce',
			'グライガー': 'Gligar',
			'ハガネール': 'Steelix',
			'ブルー': 'Snubbull',
			'グランブル': 'Granbull',
			'ハリーセン': 'Qwilfish',
			'ハッサム': 'Scizor',
			'ツボツボ': 'Shuckle',
			'ヘラクロス': 'Heracross',
			'ニューラ': 'Sneasel',
			'ヒメグマ': 'Teddiursa',
			'リングマ': 'Ursaring',
			'マグマッグ': 'Slugma',
			'マグカルゴ': 'Magcargo',
			'ウリムー': 'Swinub',
			'イノムー': 'Piloswine',
			'サニーゴ': 'Corsola',
			'テッポウオ': 'Remoraid',
			'オクタン': 'Octillery',
			'デリバード': 'Delibird',
			'マンタイン': 'Mantine',
			'エアームド': 'Skarmory',
			'デルビル': 'Houndour',
			'ヘルガー': 'Houndoom',
			'キングドラ': 'Kingdra',
			'ゴマゾウ': 'Phanpy',
			'ドンファン': 'Donphan',
			'ポリゴン２': 'Porygon2',
			'オドシシ': 'Stantler',
			'ドーブル': 'Smeargle',
			'バルキー': 'Tyrogue',
			'カポエラー': 'Hitmontop',
			'ムチュール': 'Smoochum',
			'エレキッド': 'Elekid',
			'ブビィ': 'Magby',
			'ミルタンク': 'Miltank',
			'ハピナス': 'Blissey',
			'ライコウ': 'Raikou',
			'エンテイ': 'Entei',
			'スイクン': 'Suicune',
			'ヨーギラス': 'Larvitar',
			'サナギラス': 'Pupitar',
			'バンギラス': 'Tyranitar',
			'ルギア': 'Lugia',
			'ホウオウ': 'Ho-Oh',
			'セレビィ': 'Celebi',
			'キモリ': 'Treecko',
			'ジュプトル': 'Grovyle',
			'ジュカイン': 'Sceptile',
			'アチャモ': 'Torchic',
			'ワカシャモ': 'Combusken',
			'バシャーモ': 'Blaziken',
			'ミズゴロウ': 'Mudkip',
			'ヌマクロー': 'Marshtomp',
			'ラグラージ': 'Swampert',
			'ポチエナ': 'Poochyena',
			'グラエナ': 'Mightyena',
			'ジグザグマ': 'Zigzagoon',
			'マッスグマ': 'Linoone',
			'ケムッソ': 'Wurmple',
			'カラサリス': 'Silcoon',
			'アゲハント': 'Beautifly',
			'マユルド': 'Cascoon',
			'ドクケイル': 'Dustox',
			'ハスボー': 'Lotad',
			'ハスブレロ': 'Lombre',
			'ルンパッパ': 'Ludicolo',
			'タネボー': 'Seedot',
			'コノハナ': 'Nuzleaf',
			'ダーテング': 'Shiftry',
			'スバメ': 'Taillow',
			'オオスバメ': 'Swellow',
			'キャモメ': 'Wingull',
			'ペリッパー': 'Pelipper',
			'ラルトス': 'Ralts',
			'キルリア': 'Kirlia',
			'サーナイト': 'Gardevoir',
			'アメタマ': 'Surskit',
			'アメモース': 'Masquerain',
			'キノココ': 'Shroomish',
			'キノガッサ': 'Breloom',
			'ナマケロ': 'Slakoth',
			'ヤルキモノ': 'Vigoroth',
			'ケッキング': 'Slaking',
			'ツチニン': 'Nincada',
			'テッカニン': 'Ninjask',
			'ヌケニン': 'Shedinja',
			'ゴニョニョ': 'Whismur',
			'ドゴーム': 'Loudred',
			'バクオング': 'Exploud',
			'マクノシタ': 'Makuhita',
			'ハリテヤマ': 'Hariyama',
			'ルリリ': 'Azurill',
			'ノズパス': 'Nosepass',
			'エネコ': 'Skitty',
			'エネコロロ': 'Delcatty',
			'ヤミラミ': 'Sableye',
			'クチート': 'Mawile',
			'ココドラ': 'Aron',
			'コドラ': 'Lairon',
			'ボスゴドラ': 'Aggron',
			'アサナン': 'Meditite',
			'チャーレム': 'Medicham',
			'ラクライ': 'Electrike',
			'ライボルト': 'Manectric',
			'プラスル': 'Plusle',
			'マイナン': 'Minun',
			'バルビート': 'Volbeat',
			'イルミーゼ': 'Illumise',
			'ロゼリア': 'Roselia',
			'ゴクリン': 'Gulpin',
			'マルノーム': 'Swalot',
			'キバニア': 'Carvanha',
			'サメハダー': 'Sharpedo',
			'ホエルコ': 'Wailmer',
			'ホエルオー': 'Wailord',
			'ドンメル': 'Numel',
			'バクーダ': 'Camerupt',
			'コータス': 'Torkoal',
			'バネブー': 'Spoink',
			'ブーピッグ': 'Grumpig',
			'パッチール': 'Spinda',
			'ナックラー': 'Trapinch',
			'ビブラーバ': 'Vibrava',
			'フライゴン': 'Flygon',
			'サボネア': 'Cacnea',
			'ノクタス': 'Cacturne',
			'チルット': 'Swablu',
			'チルタリス': 'Altaria',
			'ザングース': 'Zangoose',
			'ハブネーク': 'Seviper',
			'ルナトーン': 'Lunatone',
			'ソルロック': 'Solrock',
			'ドジョッチ': 'Barboach',
			'ナマズン': 'Whiscash',
			'ヘイガニ': 'Corphish',
			'シザリガー': 'Crawdaunt',
			'ヤジロン': 'Baltoy',
			'ネンドール': 'Claydol',
			'リリーラ': 'Lileep',
			'ユレイドル': 'Cradily',
			'アノプス': 'Anorith',
			'アーマルド': 'Armaldo',
			'ヒンバス': 'Feebas',
			'ミロカロス': 'Milotic',
			'ポワルン': 'Castform',
			'カクレオン': 'Kecleon',
			'カゲボウズ': 'Shuppet',
			'ジュペッタ': 'Banette',
			'ヨマワル': 'Duskull',
			'サマヨール': 'Dusclops',
			'トロピウス': 'Tropius',
			'チリーン': 'Chimecho',
			'アブソル': 'Absol',
			'ソーナノ': 'Wynaut',
			'ユキワラシ': 'Snorunt',
			'オニゴーリ': 'Glalie',
			'タマザラシ': 'Spheal',
			'トドグラー': 'Sealeo',
			'トドゼルガ': 'Walrein',
			'パールル': 'Clamperl',
			'ハンテール': 'Huntail',
			'サクラビス': 'Gorebyss',
			'ジーランス': 'Relicanth',
			'ラブカス': 'Luvdisc',
			'タツベイ': 'Bagon',
			'コモルー': 'Shelgon',
			'ボーマンダ': 'Salamence',
			'ダンバル': 'Beldum',
			'メタング': 'Metang',
			'メタグロス': 'Metagross',
			'レジロック': 'Regirock',
			'レジアイス': 'Regice',
			'レジスチル': 'Registeel',
			'ラティアス': 'Latias',
			'ラティオス': 'Latios',
			'カイオーガ': 'Kyogre',
			'グラードン': 'Groudon',
			'レックウザ': 'Rayquaza',
			'ジラーチ': 'Jirachi',
			'デオキシス': 'Deoxys',
			'ナエトル': 'Turtwig',
			'ハヤシガメ': 'Grotle',
			'ドダイトス': 'Torterra',
			'ヒコザル': 'Chimchar',
			'モウカザル': 'Monferno',
			'ゴウカザル': 'Infernape',
			'ポッチャマ': 'Piplup',
			'ポッタイシ': 'Prinplup',
			'エンペルト': 'Empoleon',
			'ムックル': 'Starly',
			'ムクバード': 'Staravia',
			'ムクホーク': 'Staraptor',
			'ビッパ': 'Bidoof',
			'ビーダル': 'Bibarel',
			'コロボーシ': 'Kricketot',
			'コロトック': 'Kricketune',
			'コリンク': 'Shinx',
			'ルクシオ': 'Luxio',
			'レントラー': 'Luxray',
			'スボミー': 'Budew',
			'ロズレイド': 'Roserade',
			'ズガイドス': 'Cranidos',
			'ラムパルド': 'Rampardos',
			'タテトプス': 'Shieldon',
			'トリデプス': 'Bastiodon',
			'ミノムッチ': 'Burmy',
			'ミノマダム': 'Wormadam',
			'ガーメイル': 'Mothim',
			'ミツハニー': 'Combee',
			'ビークイン': 'Vespiquen',
			'パチリス': 'Pachirisu',
			'ブイゼル': 'Buizel',
			'フローゼル': 'Floatzel',
			'チェリンボ': 'Cherubi',
			'チェリム': 'Cherrim',
			'カラナクシ': 'Shellos',
			'トリトドン': 'Gastrodon',
			'エテボース': 'Ambipom',
			'フワンテ': 'Drifloon',
			'フワライド': 'Drifblim',
			'ミミロル': 'Buneary',
			'ミミロップ': 'Lopunny',
			'ムウマージ': 'Mismagius',
			'ドンカラス': 'Honchkrow',
			'ニャルマー': 'Glameow',
			'ブニャット': 'Purugly',
			'リーシャン': 'Chingling',
			'スカンプー': 'Stunky',
			'スカタンク': 'Skuntank',
			'ドーミラー': 'Bronzor',
			'ドータクン': 'Bronzong',
			'ウソハチ': 'Bonsly',
			'マネネ': 'Mime Jr.',
			'ピンプク': 'Happiny',
			'ペラップ': 'Chatot',
			'ミカルゲ': 'Spiritomb',
			'フカマル': 'Gible',
			'ガバイト': 'Gabite',
			'ガブリアス': 'Garchomp',
			'ゴンベ': 'Munchlax',
			'リオル': 'Riolu',
			'ルカリオ': 'Lucario',
			'ヒポポタス': 'Hippopotas',
			'カバルドン': 'Hippowdon',
			'スコルピ': 'Skorupi',
			'ドラピオン': 'Drapion',
			'グレッグル': 'Croagunk',
			'ドクロッグ': 'Toxicroak',
			'マスキッパ': 'Carnivine',
			'ケイコウオ': 'Finneon',
			'ネオラント': 'Lumineon',
			'タマンタ': 'Mantyke',
			'ユキカブリ': 'Snover',
			'ユキノオー': 'Abomasnow',
			'マニューラ': 'Weavile',
			'ジバコイル': 'Magnezone',
			'ベロベルト': 'Lickilicky',
			'ドサイドン': 'Rhyperior',
			'モジャンボ': 'Tangrowth',
			'エレキブル': 'Electivire',
			'ブーバーン': 'Magmortar',
			'トゲキッス': 'Togekiss',
			'メガヤンマ': 'Yanmega',
			'リーフィア': 'Leafeon',
			'グレイシア': 'Glaceon',
			'グライオン': 'Gliscor',
			'マンムー': 'Mamoswine',
			'ポリゴンZ': 'Porygon-Z',
			'エルレイド': 'Gallade',
			'ダイノーズ': 'Probopass',
			'ヨノワール': 'Dusknoir',
			'ユキメノコ': 'Froslass',
			'ロトム': 'Rotom',
			'ユクシー': 'Uxie',
			'エムリット': 'Mesprit',
			'アグノム': 'Azelf',
			'ディアルガ': 'Dialga',
			'パルキア': 'Palkia',
			'ヒードラン': 'Heatran',
			'レジギガス': 'Regigigas',
			'ギラティナ': 'Giratina',
			'クレセリア': 'Cresselia',
			'フィオネ': 'Phione',
			'マナフィ': 'Manaphy',
			'ダークライ': 'Darkrai',
			'シェイミ': 'Shaymin',
			'アルセウス': 'Arceus',
			'ビクティニ': 'Victini',
			'ツタージャ': 'Snivy',
			'ジャノビー': 'Servine',
			'ジャローダ': 'Serperior',
			'ポカブ': 'Tepig',
			'チャオブー': 'Pignite',
			'エンブオー': 'Emboar',
			'ミジュマル': 'Oshawott',
			'フタチマル': 'Dewott',
			'ダイケンキ': 'Samurott',
			'ミネズミ': 'Patrat',
			'ミルホッグ': 'Watchog',
			'ヨーテリー': 'Lillipup',
			'ハーデリア': 'Herdier',
			'ムーランド': 'Stoutland',
			'チョロネコ': 'Purrloin',
			'レパルダス': 'Liepard',
			'ヤナップ': 'Pansage',
			'ヤナッキー': 'Simisage',
			'バオップ': 'Pansear',
			'バオッキー': 'Simisear',
			'ヒヤップ': 'Panpour',
			'ヒヤッキー': 'Simipour',
			'ムンナ': 'Munna',
			'ムシャーナ': 'Musharna',
			'マメパト': 'Pidove',
			'ハトーボー': 'Tranquill',
			'ケンホロウ': 'Unfezant',
			'シママ': 'Blitzle',
			'ゼブライカ': 'Zebstrika',
			'ダンゴロ': 'Roggenrola',
			'ガントル': 'Boldore',
			'ギガイアス': 'Gigalith',
			'コロモリ': 'Woobat',
			'ココロモリ': 'Swoobat',
			'モグリュー': 'Drilbur',
			'ドリュウズ': 'Excadrill',
			'タブンネ': 'Audino',
			'ドッコラー': 'Timburr',
			'ドテッコツ': 'Gurdurr',
			'ローブシン': 'Conkeldurr',
			'オタマロ': 'Tympole',
			'ガマガル': 'Palpitoad',
			'ガマゲロゲ': 'Seismitoad',
			'ナゲキ': 'Throh',
			'ダゲキ': 'Sawk',
			'クルミル': 'Sewaddle',
			'クルマユ': 'Swadloon',
			'ハハコモリ': 'Leavanny',
			'フシデ': 'Venipede',
			'ホイーガ': 'Whirlipede',
			'ペンドラー': 'Scolipede',
			'モンメン': 'Cottonee',
			'エルフーン': 'Whimsicott',
			'チュリネ': 'Petilil',
			'ドレディア': 'Lilligant',
			'バスラオ': 'Basculin',
			'メグロコ': 'Sandile',
			'ワルビル': 'Krokorok',
			'ワルビアル': 'Krookodile',
			'ダルマッカ': 'Darumaka',
			'ヒヒダルマ': 'Darmanitan',
			'マラカッチ': 'Maractus',
			'イシズマイ': 'Dwebble',
			'イワパレス': 'Crustle',
			'ズルッグ': 'Scraggy',
			'ズルズキン': 'Scrafty',
			'シンボラー': 'Sigilyph',
			'デスマス': 'Yamask',
			'デスカーン': 'Cofagrigus',
			'プロトーガ': 'Tirtouga',
			'アバゴーラ': 'Carracosta',
			'アーケン': 'Archen',
			'アーケオス': 'Archeops',
			'ヤブクロン': 'Trubbish',
			'ダストダス': 'Garbodor',
			'ゾロア': 'Zorua',
			'ゾロアーク': 'Zoroark',
			'チラーミィ': 'Minccino',
			'チラチーノ': 'Cinccino',
			'ゴチム': 'Gothita',
			'ゴチミル': 'Gothorita',
			'ゴチルゼル': 'Gothitelle',
			'ユニラン': 'Solosis',
			'ダブラン': 'Duosion',
			'ランクルス': 'Reuniclus',
			'コアルヒー': 'Ducklett',
			'スワンナ': 'Swanna',
			'バニプッチ': 'Vanillite',
			'バニリッチ': 'Vanillish',
			'バイバニラ': 'Vanilluxe',
			'シキジカ': 'Deerling',
			'メブキジカ': 'Sawsbuck',
			'エモンガ': 'Emolga',
			'カブルモ': 'Karrablast',
			'シュバルゴ': 'Escavalier',
			'タマゲタケ': 'Foongus',
			'モロバレル': 'Amoonguss',
			'プルリル': 'Frillish',
			'ブルンゲル': 'Jellicent',
			'ママンボウ': 'Alomomola',
			'バチュル': 'Joltik',
			'デンチュラ': 'Galvantula',
			'テッシード': 'Ferroseed',
			'ナットレイ': 'Ferrothorn',
			'ギアル': 'Klink',
			'ギギアル': 'Klang',
			'ギギギアル': 'Klinklang',
			'シビシラス': 'Tynamo',
			'シビビール': 'Eelektrik',
			'シビルドン': 'Eelektross',
			'リグレー': 'Elgyem',
			'オーベム': 'Beheeyem',
			'ヒトモシ': 'Litwick',
			'ランプラー': 'Lampent',
			'シャンデラ': 'Chandelure',
			'キバゴ': 'Axew',
			'オノンド': 'Fraxure',
			'オノノクス': 'Haxorus',
			'クマシュン': 'Cubchoo',
			'ツンベアー': 'Beartic',
			'フリージオ': 'Cryogonal',
			'チョボマキ': 'Shelmet',
			'アギルダー': 'Accelgor',
			'マッギョ': 'Stunfisk',
			'コジョフー': 'Mienfoo',
			'コジョンド': 'Mienshao',
			'クリムガン': 'Druddigon',
			'ゴビット': 'Golett',
			'ゴルーグ': 'Golurk',
			'コマタナ': 'Pawniard',
			'キリキザン': 'Bisharp',
			'バッフロン': 'Bouffalant',
			'ワシボン': 'Rufflet',
			'ウォーグル': 'Braviary',
			'バルチャイ': 'Vullaby',
			'バルジーナ': 'Mandibuzz',
			'クイタラン': 'Heatmor',
			'アイアント': 'Durant',
			'モノズ': 'Deino',
			'ジヘッド': 'Zweilous',
			'サザンドラ': 'Hydreigon',
			'メラルバ': 'Larvesta',
			'ウルガモス': 'Volcarona',
			'コバルオン': 'Cobalion',
			'テラキオン': 'Terrakion',
			'ビリジオン': 'Virizion',
			'トルネロス': 'Tornadus',
			'ボルトロス': 'Thundurus',
			'レシラム': 'Reshiram',
			'ゼクロム': 'Zekrom',
			'ランドロス': 'Landorus',
			'キュレム': 'Kyurem',
			'ケルディオ': 'Keldeo',
			'メロエッタ': 'Meloetta',
			'ゲノセクト': 'Genesect',
			'ハリマロン': 'Chespin',
			'ハリボーグ': 'Quilladin',
			'ブリガロン': 'Chesnaught',
			'フォッコ': 'Fennekin',
			'テールナー': 'Braixen',
			'マフォクシー': 'Delphox',
			'ケロマツ': 'Froakie',
			'ゲコガシラ': 'Frogadier',
			'ゲッコウガ': 'Greninja',
			'ホルビー': 'Bunnelby',
			'ホルード': 'Diggersby',
			'ヤヤコマ': 'Fletchling',
			'ヒノヤコマ': 'Fletchinder',
			'ファイアロー': 'Talonflame',
			'コフキムシ': 'Scatterbug',
			'コフーライ': 'Spewpa',
			'ビビヨン': 'Vivillon',
			'シシコ': 'Litleo',
			'カエンジシ': 'Pyroar',
			'フラベベ': 'Flabébé',
			'フラエッテ': 'Floette',
			'フラージェス': 'Florges',
			'メェークル': 'Skiddo',
			'ゴーゴート': 'Gogoat',
			'ヤンチャム': 'Pancham',
			'ゴロンダ': 'Pangoro',
			'トリミアン': 'Furfrou',
			'ニャスパー': 'Espurr',
			'ニャオニクス': 'Meowstic',
			'ヒトツキ': 'Honedge',
			'ニダンギル': 'Doublade',
			'ギルガルド': 'Aegislash',
			'シュシュプ': 'Spritzee',
			'フレフワン': 'Aromatisse',
			'ペロッパフ': 'Swirlix',
			'ペロリーム': 'Slurpuff',
			'マーイーカ': 'Inkay',
			'カラマネロ': 'Malamar',
			'カメテテ': 'Binacle',
			'ガメノデス': 'Barbaracle',
			'クズモー': 'Skrelp',
			'ドラミドロ': 'Dragalge',
			'ウデッポウ': 'Clauncher',
			'ブロスター': 'Clawitzer',
			'エリキテル': 'Helioptile',
			'エレザード': 'Heliolisk',
			'チゴラス': 'Tyrunt',
			'ガチゴラス': 'Tyrantrum',
			'アマルス': 'Amaura',
			'アマルルガ': 'Aurorus',
			'ニンフィア': 'Sylveon',
			'ルチャブル': 'Hawlucha',
			'デデンネ': 'Dedenne',
			'メレシー': 'Carbink',
			'ヌメラ': 'Goomy',
			'ヌメイル': 'Sliggoo',
			'ヌメルゴン': 'Goodra',
			'クレッフィ': 'Klefki',
			'ボクレー': 'Phantump',
			'オーロット': 'Trevenant',
			'バケッチャ': 'Pumpkaboo',
			'パンプジン': 'Gourgeist',
			'カチコール': 'Bergmite',
			'クレベース': 'Avalugg',
			'オンバット': 'Noibat',
			'オンバーン': 'Noivern',
			'ゼルネアス': 'Xerneas',
			'イベルタル': 'Yveltal',
			'ジガルデ': 'Zygarde',
			'ディアンシー': 'Diancie',
			'フーパ': 'Hoopa',
			'ボルケニオン': 'Volcanion',
			'モクロー': 'Rowlet',
			'フクスロー': 'Dartrix',
			'ジュナイパー': 'Decidueye',
			'ニャビー': 'Litten',
			'ニャヒート': 'Torracat',
			'ガオガエン': 'Incineroar',
			'アシマリ': 'Popplio',
			'オシャマリ': 'Brionne',
			'アシレーヌ': 'Primarina',
			'ツツケラ': 'Pikipek',
			'ケララッパ': 'Trumbeak',
			'ドデカバシ': 'Toucannon',
			'ヤングース': 'Yungoos',
			'デカグース': 'Gumshoos',
			'アゴジムシ': 'Grubbin',
			'デンヂムシ': 'Charjabug',
			'クワガノン': 'Vikavolt',
			'マケンカニ': 'Crabrawler',
			'ケケンカニ': 'Crabominable',
			'オドリドリ': 'Oricorio',
			'アブリー': 'Cutiefly',
			'アブリボン': 'Ribombee',
			'イワンコ': 'Rockruff',
			'ルガルガン': 'Lycanroc',
			'ヨワシ': 'Wishiwashi',
			'ヒドイデ': 'Mareanie',
			'ドヒドイデ': 'Toxapex',
			'ドロバンコ': 'Mudbray',
			'バンバドロ': 'Mudsdale',
			'シズクモ': 'Dewpider',
			'オニシズクモ': 'Araquanid',
			'カリキリ': 'Fomantis',
			'ラランテス': 'Lurantis',
			'ネマシュ': 'Morelull',
			'マシェード': 'Shiinotic',
			'ヤトウモリ': 'Salandit',
			'エンニュート': 'Salazzle',
			'ヌイコグマ': 'Stufful',
			'キテルグマ': 'Bewear',
			'アマカジ': 'Bounsweet',
			'アママイコ': 'Steenee',
			'アマージョ': 'Tsareena',
			'キュワワー': 'Comfey',
			'ヤレユータン': 'Oranguru',
			'ナゲツケサル': 'Passimian',
			'コソクムシ': 'Wimpod',
			'グソクムシャ': 'Golisopod',
			'スナバァ': 'Sandygast',
			'シロデスナ': 'Palossand',
			'ナマコブシ': 'Pyukumuku',
			'タイプ：ヌル': 'Type: Null',
			'シルヴァディ': 'Silvally',
			'メテノ': 'Minior',
			'ネッコアラ': 'Komala',
			'バクガメス': 'Turtonator',
			'トゲデマル': 'Togedemaru',
			'ミミッキュ': 'Mimikyu',
			'ハギギシリ': 'Bruxish',
			'ジジーロン': 'Drampa',
			'ダダリン': 'Dhelmise',
			'ジャラコ': 'Jangmo-o',
			'ジャランゴ': 'Hakamo-o',
			'ジャラランガ': 'Kommo-o',
			'カプ・コケコ': 'Tapu Koko',
			'カプ・テテフ': 'Tapu Lele',
			'カプ・ブルル': 'Tapu Bulu',
			'カプ・レヒレ': 'Tapu Fini',
			'コケコ': 'Koko',
			'テテフ': 'Lele',
			'ブルル': 'Bulu',
			'レヒレ': 'Fini',
			'カプ': 'Tapu ',
			'コスモッグ': 'Cosmog',
			'コスモウム': 'Cosmoem',
			'ソルガレオ': 'Solgaleo',
			'ルナアーラ': 'Lunala',
			'ウツロイド': 'Nihilego',
			'マッシブーン': 'Buzzwole',
			'フェローチェ': 'Pheromosa',
			'デンジュモク': 'Xurkitree',
			'テッカグヤ': 'Celesteela',
			'カミツルギ': 'Kartana',
			'アクジキング': 'Guzzlord',
			'ネクロズマ': 'Necrozma',
			'マギアナ': 'Magearna',
			'マーシャドー': 'Marshadow',
			'ベベノム': 'Poipole',
			'アーゴヨン': 'Naganadel',
			'ツンデツンデ': 'Stakataka',
			'ズガドーン': 'Blacephalon',
			'ゼラオラ': 'Zeraora',

			// TYPES

			'ノーマル': 'Normal',
			'ほのお': 'Fire',
			'かくとう': 'Fighting',
			'みず': 'Water',
			'ひこう': 'Flying',
			'くさ': 'Grass',
			'どく': 'Poison',
			'でんき': 'Electric',
			'じめん': 'Ground',
			'エスパー': 'Psychic',
			'いわ': 'Rock',
			'こおり': 'Ice',
			'氷': 'Ice',
			'むし': 'Bug',
			'ドラゴン': 'Dragon',
			'ゴーストタイプ': 'Ghost',
			'あく': 'Dark',
			'はがね': 'Steel',
			'フェアリー': 'Fairy',

			// BERRIES

			'クラボ': 'Cheri',
			'カゴ': 'Chesto',
			'モモン': 'Pecha',
			'チーゴ': 'Rawst',
			'ナナシ': 'Aspear',
			'ヒメリ': 'Leppa',
			'オレン': 'Oran',
			'キー': 'Persim',
			'ラム': 'Lum',
			'オボン': 'Sitrus',
			'フィラ': 'Figy',
			'ウイ': 'Wiki',
			'マゴ': 'Mago',
			'バンジ': 'Aguav',
			'イア': 'Iapapa',
			'ズリ': 'Razz',
			'ブリー': 'Bluk',
			'ナナ': 'Nanab',
			'セシナ': 'Wepear',
			'パイル': 'Pinap',
			'ザロク': 'Pomeg',
			'ネコブ': 'Kelpsy',
			'タポル': 'Qualot',
			'ロメ': 'Hondew',
			'ウブ': 'Grepa',
			'マトマ': 'Tamato',
			'モコシ': 'Cornn',
			'ゴス': 'Magost',
			'ラブタ': 'Rabuta',
			'ノメル': 'Nomel',
			'ノワキ': 'Spelon',
			'シーヤ': 'Pamtre',
			'カイス': 'Watmel',
			'ドリ': 'Durin',
			'ベリブ': 'Belue',
			'チイラ': 'Liechi',
			'リュガ': 'Ganlon',
			'カムラ': 'Salac',
			'ヤタピ': 'Petaya',
			'ズア': 'Apicot',
			'サン': 'Lansat',
			'スター': 'Starf',
			'ナゾ': 'Enigma',
			'オッカ': 'Occa',
			'イトケ': 'Passho',
			'ソクノ': 'Wacan',
			'リンド': 'Rindo',
			'ヤチェ': 'Yache',
			'ヨプ': 'Chople',
			'ビアー': 'Kebia',
			'シュカ': 'Shuca',
			'バコウ': 'Coba',
			'ウタン': 'Payapa',
			'タンガ': 'Tanga',
			'ヨロギ': 'Charti',
			'カシブ': 'Kasib',
			'ハバン': 'Haban',
			'ナモ': 'Colbur',
			'リリバ': 'Babiri',
			'ホズ': 'Chilan',
			'ミクル': 'Micle',
			'イバン': 'Custap',
			'ジャポ': 'Jaboca',
			'レンブ': 'Rowap',
			'ロゼル': 'Roseli',
			'アッキ': 'Kee',
			'タラプ': 'Maranga',
			'のみ': ' Berry',

			// MISC

			'霊獣': 'Therian',
			'性格': 'Nature',
			'実数値': 'Stats',
			'努力値': 'EVs',
			'特性': 'Ability',
			'持ち物': 'Item',
			'技構成': 'Moves'
		}
	}
};